const cfg=window.APP_CONFIG||{};const db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const statusList=["Todo","Ongoing","Done"];let currentUser=null,tasks=[],logs={},savedLogs={};let activeLogDate="";
function formatLocalDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function todayString(){return formatLocalDate(new Date())}function addDays(s,n){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s||"");const d=m?new Date(+m[1],+m[2]-1,+m[3]):new Date();d.setDate(d.getDate()+n);return formatLocalDate(d)}function esc(t){return String(t||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function toast(t){const e=document.createElement("div");e.className="toast";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}
function bindTabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")})}
async function signIn(){const email=loginEmail.value.trim(),password=loginPassword.value;const{error}=await db.auth.signInWithPassword({email,password});loginMessage.textContent=error?error.message:""}async function signUp(){const email=loginEmail.value.trim(),password=loginPassword.value;const{error}=await db.auth.signUp({email,password});loginMessage.textContent=error?error.message:"Account created. Check your email if confirmation is enabled."}async function signOut(){await db.auth.signOut()}
async function loadTasks(){const{data,error}=await db.from("tasks").select("*").order("updated_at",{ascending:false});if(error)throw error;tasks=data||[];renderTasks()}async function loadLogs(){const{data,error}=await db.from("daily_logs").select("*");if(error)throw error;logs={};savedLogs={};(data||[]).forEach(r=>{savedLogs[r.log_date]={...r};logs[r.log_date]={...r,_draft:false}});loadLogForDate()}
async function addTask(){const title=taskTitle.value.trim();if(!title)return alert("Please enter task title.");const{error}=await db.from("tasks").insert({user_id:currentUser.id,title,description:taskDesc.value.trim(),priority:taskPriority.value,status:"Todo",deadline:taskDeadline.value||null});if(error)return alert(error.message);taskTitle.value="";taskDesc.value="";taskPriority.value="Medium";taskDeadline.value="";await loadTasks();toast("Task saved.")}
async function moveTask(id,status){const{error}=await db.from("tasks").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)return alert(error.message);await loadTasks()}async function deleteTask(id){if(!confirm("Delete selected task?"))return;const{error}=await db.from("tasks").delete().eq("id",id);if(error)return alert(error.message);await loadTasks()}
function openEditTask(id){const t=tasks.find(x=>String(x.id)===String(id));if(!t)return;editTaskId.value=t.id;editTaskTitle.value=t.title||"";editTaskPriority.value=t.priority||"Medium";editTaskDeadline.value=t.deadline||"";editTaskDesc.value=t.description||"";editModal.classList.remove("hidden")}function closeEditTask(){editModal.classList.add("hidden")}async function saveEditTask(){const id=editTaskId.value,title=editTaskTitle.value.trim();if(!title)return alert("Please enter task title.");const{error}=await db.from("tasks").update({title,priority:editTaskPriority.value,deadline:editTaskDeadline.value||null,description:editTaskDesc.value.trim(),updated_at:new Date().toISOString()}).eq("id",id);if(error)return alert(error.message);closeEditTask();await loadTasks();toast("Task updated.")}
function rank(p){return p==="High"?1:p==="Medium"?2:3}function renderTasks(){const map={Todo:todoList,Ongoing:ongoingList,Done:doneList};Object.values(map).forEach(e=>e.innerHTML="");[...tasks].sort((a,b)=>rank(a.priority)-rank(b.priority)||String(b.updated_at).localeCompare(String(a.updated_at))).forEach(t=>{const c=document.createElement("article");c.className="task-card";const moves=statusList.filter(s=>s!==t.status).map(s=>`<button class="btn secondary" data-move="${s}" data-id="${t.id}">${s}</button>`).join("");const description=t.description?`<details class="task-description"><summary><span class="show-label">Show description</span><span class="hide-label">Hide description</span></summary><p class="task-desc">${esc(t.description)}</p></details>`:"";const overdue=Boolean(t.deadline&&t.status!=="Done"&&t.deadline<todayString());const deadline=t.deadline?`<div class="task-deadline${overdue?" overdue":""}">${overdue?"Overdue · ":"Deadline · "}${esc(t.deadline)}</div>`:"";c.innerHTML=`<div class="task-head"><div class="task-title">${esc(t.title)}</div><span class="badge">${esc(t.priority)}</span></div>${deadline}${description}<div class="task-actions">${moves}<button class="btn primary" data-edit="${t.id}">Edit</button><button class="btn danger" data-delete="${t.id}">Delete</button></div>`;map[t.status]?.appendChild(c)});document.querySelectorAll("[data-move]").forEach(b=>b.onclick=()=>moveTask(b.dataset.id,b.dataset.move));document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEditTask(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteTask(b.dataset.delete))}
function cleanLogValues(v={}){return{completed:String(v.completed||""),ongoing:String(v.ongoing||""),blockers:String(v.blockers||""),next_plan:String(v.next_plan||"")}}function currentLogValues(){return cleanLogValues({completed:completed.value,ongoing:ongoing.value,blockers:blockers.value,next_plan:nextPlan.value})}function sameLogValues(a,b){const x=cleanLogValues(a),y=cleanLogValues(b);return x.completed===y.completed&&x.ongoing===y.ongoing&&x.blockers===y.blockers&&x.next_plan===y.next_plan}function isDateUnsaved(d,values){return !sameLogValues(values??logs[d]??{},savedLogs[d]??{})}
function setSaveStatus(isUnsaved){saveStatus.textContent=isUnsaved?"Unsaved changes":"Saved";saveStatus.classList.toggle("unsaved",isUnsaved);saveStatus.classList.toggle("saved",!isUnsaved)}
function cacheCurrentLog(){if(!activeLogDate)return;const values=currentLogValues(),old=logs[activeLogDate]||{};const dirty=isDateUnsaved(activeLogDate,values);logs[activeLogDate]={...old,log_date:activeLogDate,...values,_draft:dirty};if((logDate.value||todayString())===activeLogDate)setSaveStatus(dirty)}
function loadLogForDate(){const d=logDate.value||todayString(),r=logs[d]||savedLogs[d]||{};completed.value=r.completed||"";ongoing.value=r.ongoing||"";blockers.value=r.blockers||"";nextPlan.value=r.next_plan||"";activeLogDate=d;setSaveStatus(isDateUnsaved(d,r))}
function switchLogDate(newDate){cacheCurrentLog();logDate.value=newDate;loadLogForDate()}
function markCurrentLogUnsaved(){if(!activeLogDate)activeLogDate=logDate.value||todayString();const values=currentLogValues(),old=logs[activeLogDate]||{};const dirty=isDateUnsaved(activeLogDate,values);logs[activeLogDate]={...old,log_date:activeLogDate,...values,_draft:dirty};setSaveStatus(dirty)}
async function saveLog(){const d=logDate.value||todayString();cacheCurrentLog();const submitted=cleanLogValues(logs[d]||currentLogValues());const payload={user_id:currentUser.id,log_date:d,...submitted,updated_at:new Date().toISOString()};saveLogBtn.disabled=true;if((logDate.value||todayString())===d)saveStatus.textContent="Saving...";const{data,error}=await db.from("daily_logs").upsert(payload,{onConflict:"user_id,log_date"}).select().single();saveLogBtn.disabled=false;if(error){if((logDate.value||todayString())===d)setSaveStatus(true);return alert(error.message)}const savedRow=data||payload;savedLogs[d]={...savedRow};const currentDraft=logs[d]||submitted;const stillDirty=!sameLogValues(currentDraft,submitted);logs[d]={...savedRow,...cleanLogValues(currentDraft),_draft:stillDirty};if((logDate.value||todayString())===d){if(activeLogDate===d){const liveValues=currentLogValues();const liveDirty=!sameLogValues(liveValues,submitted);logs[d]={...savedRow,...liveValues,_draft:liveDirty};setSaveStatus(liveDirty)}else setSaveStatus(stillDirty)}toast("Daily work log saved.")}
function changeDay(n){switchLogDate(addDays(logDate.value||todayString(),n))}
async function showApp(session){currentUser=session.user;loginView.classList.add("hidden");appView.classList.remove("hidden");userEmail.textContent=currentUser.email||"";if(!logDate.value)logDate.value=todayString();await Promise.all([loadTasks(),loadLogs()])}function showLogin(){currentUser=null;activeLogDate="";logs={};savedLogs={};appView.classList.add("hidden");loginView.classList.remove("hidden")}
async function init(){bindTabs();loginBtn.onclick=signIn;signupBtn.onclick=signUp;logoutBtn.onclick=signOut;addTaskBtn.onclick=addTask;prevDayBtn.onclick=()=>changeDay(-1);todayBtn.onclick=()=>switchLogDate(todayString());nextDayBtn.onclick=()=>changeDay(1);logDate.onchange=()=>{const newDate=logDate.value||todayString();cacheCurrentLog();logDate.value=newDate;loadLogForDate()};[completed,ongoing,blockers,nextPlan].forEach(el=>el.addEventListener("input",markCurrentLogUnsaved));saveLogBtn.onclick=saveLog;saveEditTaskBtn.onclick=saveEditTask;cancelEditTaskBtn.onclick=closeEditTask;closeEditModalBtn.onclick=closeEditTask;const{data:{session}}=await db.auth.getSession();session?await showApp(session):showLogin();db.auth.onAuthStateChange(async(event,session)=>{if(event==="SIGNED_OUT"){showLogin();return}if(event==="SIGNED_IN"&&session){if(!currentUser)await showApp(session);else currentUser=session.user}})}init();
